# Site title and subtitle. This is used in _includes/header.html
title: Vladislav Kochetov
subtitle: |
  Personal site of Vladislav Kochetov,
  tech blog and personal projects.
description: Mobile Software Engineer

baseurl: ""

author:
  name: Vladislav Kochetov
  email: "hello@vladleesi.dev"

collections:
  projects:
    output: true

# Build settings
exclude: [ 'bin', 'README.md' ]
markdown: kramdown
remote_theme: "jekyll/minima"
minima:
  skin: auto
  nav_pages:
    - about.md
    - projects.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/vladleesi"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/vladkochetov"
    - title: dev.to
      icon: dev
      url: "https://dev.to/vladleesi"
    - title: Medium
      icon: medium
      url: "https://medium.com/@vladleesi"
    - title: Twitter
      icon: x-twitter
      url: "https://twitter.com/vladleesi"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
